# Generated by Django 5.2.6 on 2025-09-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_categoria_tipocategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
    ]
